#!/usr/bin/env sh

IMAGE_FILE=flags.svg
CSS_FILE=flags.module.scss

WORK_DIR=${TMPDIR:-${TEMP:-${TMP:-/tmp}}}

./extract_country_codes | ./to_twemoji_url | ./download_image -d $WORK_DIR/twemoji
./rename_svg $WORK_DIR/twemoji $WORK_DIR/flags
./combine_svg $WORK_DIR/flags -o $WORK_DIR/$IMAGE_FILE
./generate_css $WORK_DIR/flags -o $WORK_DIR/$CSS_FILE

rm -rf $WORK_DIR/flags

mv -f $WORK_DIR/$IMAGE_FILE ../../public/img/
mv -f $WORK_DIR/$CSS_FILE ../../src/views/form/widgets/phone/
