= 7.0 Migration Guide
:toc:
:toc-title:

:product-version-changelog: https://github.com/axelor/axelor-open-platform/blob/7.0/CHANGELOG.md

In this document, we will see the major steps to migrate from 6.1 to 7.0.

NOTE: Please check the {product-version-changelog}[change log] for detailed list of fixes, changes and improvements
introduced in 7.0

== Migrate to new front-end built on top of React

Current Angular front-end is now dropped in favor of new front-end built on top of React.

Here are the following changes due to this change :

- `npm-install` Gradle task has been removed.

=== Font Awesome icons deprecated

Font Awesome icons was used as main icons library. Now two library are used :
https://marella.github.io/material-symbols/demo/[Material Symbols] and
https://icons.getbootstrap.com/[Bootstrap Icons].

Depending on the icons used, it will try to first use `Material Symbols` if the icon exist, then fallback to
`Bootstrap icons`. To ensure easy migration steps, Font Awesome icons have been mapped to Bootstrap Icons.
Please be aware that some Font Awesome icons don't have any equivalent in Bootstrap Icons, so an apps icon will be use
instead. Missing icons will be log in console in non production mode.



