= 7.1 Migration Guide
:toc:
:toc-title:

:product-version-changelog: https://github.com/axelor/axelor-open-platform/blob/7.1/CHANGELOG.md
:gradle-7-5-8-0: https://docs.gradle.org/current/userguide/upgrading_version_7.html
:gradle-8-0-8-7: https://docs.gradle.org/current/userguide/upgrading_version_8.html

In this document, we will see the major steps to migrate from 7.0 to 7.1.

NOTE: Please check the {product-version-changelog}[change log] for detailed list of fixes, changes and improvements
introduced in 7.1

== Dependencies upgrade

Some dependencies have been upgraded to newer versions. Check the {product-version-changelog}[change log] for detailed
list.

Gradle has also been upgraded to a newer version. Upgrade the Gradle Wrapper to benefit from new features and
improvements : `./gradlew wrapper --gradle-version 8.7`.

[NOTE]
====
Note that running the wrapper task once will update `gradle-wrapper.properties` only, but leave the wrapper itself in
`gradle-wrapper.jar` untouched. This is usually fine as new versions of Gradle can be run even with ancient wrapper
files. If you nevertheless want all the wrapper files to be completely up-to-date, you’ll need to run the `wrapper`
task a second time.
====

Check Gradle migration to update your builds :

- `7.5` -> `8.0` : {gradle-7-5-8-0}[Upgrading your build from Gradle 7.x to 8.0]
- `8.0` -> `8.7` : {gradle-8-0-8-7}[Upgrading your build from Gradle 8.x to the latest]

[NOTE]
====
Gradle can display such warning : `Path for java installation '/usr/lib/jvm/openjdk-11'
(Common Linux Locations) does not contain a java executable`. It seems that Gradle will
continue to show this message if the environment is fine.

See https://github.com/gradle/gradle/issues/22921

A possible workaround is to create a symbolic link to the directory containing the `java` executable:

[source,sh]
----
cd /usr/lib/jvm/openjdk-11
sudo ln -s ../java-11-openjdk-amd64/bin .
----

====


== Kanban views

In Kanban views, the template has some automatic styles applied, especially for `img` and `h4`.
This makes different rendering and styles between cards and kanban views. In order to align them, these
automatic predefined styles has been removed in React template only. Here are the changes :

[cols="1,2,2"]
|===
| What is concerned ? | Old styles | Migration

| Any `img` elements or `Image` components
a| This put img on right bottom corner
[source,css]
----
width: 1.5rem;
height: 1.5rem;
position: absolute;
right: 0.25rem;
bottom: 0.25rem;
border-radius: 100%;
----
a| Image should be embedded in an appropriate container
[source]
----
<Image style={{ width: "1.5rem", height: "1.5rem", borderRadius: "100%" }}/>
----

| Any `h4` elements or `<Box as="h4">` components
a|
[source,css]
----
margin: 0 0 4px 0;
font-weight: 600;
font-size: 13px;
----
a|

[source]
----
<Box as="strong" mb={2}>
  {some}
</Box>
----

| Usage of `card-footer` classname
a|
[source,css]
----
margin-top: 4px;
color: #777;
font-size: 12px;
----
a|

[source]
----
<Box style={{ fontSize: "0.85rem", color: "grey" }} mt={2}>
  {some}
</Box>
----

| Usage of `css="rect-image"`
a| Apply circle image style
[source,css]
----
border-radius: 0;
----
a| Use `borderRadius` on image

[source]
----
<Image style={{ borderRadius: "100%" }}/>
----

|===

Here is a full example from legacy Angular template :

[source,html]
----
<h4>{{name}}</h4>
<img ng-if="user" ng-src="{{$image('user', 'image')}}">
<div class="card-body">{{notes}}</div>
<div class="card-footer">
    <i class='fa fa-clock-o'></i>
    <span ng-if="startDate">{{$moment(startDate).format('LLL')}}</span>
</div>
----

should be migrated in React template :

[source]
----
<Box as="strong">
    {name}
</Box>
<Box d="flex" mt={2}>
    {notes}
</Box>
<Box d="grid" gridTemplateColumns="auto auto" style={{ fontSize: "0.85rem", color: "grey" }} mt={2}>
    <Box d="flex" g={2}>
      <Icon icon={"clock"} />
      {startDate && <span>{$moment(startDate).format('LLL')}</span>}
    </Box>
    <Box d="flex" justifyContent="flex-end">
      {user && <Image src={$image('user', 'image')} style={{ width: "1.5rem", height: "1.5rem", borderRadius: "100%" }}/>}
    </Box>
</Box>
----

== `Model#cid`

We added support to identify collection items from save/action response. In order to achieve this, we
added an `cid` field in base abstract model class `Model`. This will cause conflicts with any entities already having an `cid` field. Update your entities if this is the case.

== Others Notable Changes

- Exclude archived M2O from selection : when M2O is used as a selection (`NavSelect` widget or in `Kanban#columnBy`), archived records are now excluded.
- Move view collaboration to Axelor Enterprise Edition
- Move SSO authentications to Axelor Enterprise Edition
- Remove deprecated AppInfo in favor of InfoService

Check the {product-version-changelog}[change log] for detailed list.



