= 7.2 Migration Guide
:toc:
:toc-title:

:product-version-changelog: https://github.com/axelor/axelor-open-platform/blob/7.2/CHANGELOG.md

In this document, we will see the major steps to migrate from 7.1 to 7.2.

NOTE: Please check the {product-version-changelog}[change log] for detailed list of fixes, changes and improvements
introduced in 7.2

== Region support added on translations

Similar to the current translation behavior, you can now provide translation per region : `fr-FR`, `fr-CA`, ...

To add more languages, you need to enrich the `select.language` selection. Then you can provide translations files per
region : `messages_fr-FR.csv`, `messages_fr-CA.csv`, ...

NOTE: Translations in CSV without values are not loaded anymore.

There is a translation fallback mechanism that ensures that if an exact match for a translation is not found, the
translation for the primary language is used instead. This is particularly useful for avoiding duplicate translation
effort for languages with regional variations, as well as for maintaining a consistent user experience even when some
translations are missing.

For example, if a user selects `fr-CA` (Canadian French) as their language and a specific translation is not available
in `messages_fr-CA.csv`, the translation will fall back to `messages_fr.csv` (French). If the translation is still not
found, original translation key is used, which is typically the message for the default language, `en` (English).

== String pattern validation set to be case-sensitive

String pattern validation, through the attribute `pattern`, is now case-sensitive. To manage case-insensitive, it
should be managed in regex expression itself.

Example :

- `^Foo`      : it matches string starts with `Foo`.
- `^(F|f)oo`  : it matches string starts with `foo` or `Foo`.

Note that it doesn't match the entire value but any subset. In order to match the entire value, add `^` at the start of
the pattern and a `$` at the end.

If coming from an older version (< v7),  `x-pattern` attribute was commonly used (due to historical reasons). This is
no more recommended and this attribute has no more effect. Migrate from `x-pattern` to `pattern` and adjust your regex
according. Note that `x-pattern` was matching the entire value whereas `pattern` don't.

== Deprecated icons

Two libraries are used to provides icons : Material Symbols and Bootstrap Icons. It first tries to first use Material
Symbols if the icon exist, then fallback to Bootstrap icons.

As part of our upgrades, Material Symbols icons has been removed or renamed. In order to maintain compatibility and
smooth migrations, icons that don't exist anymore has been mapped with their equivalency. Here is the list :
`arrow_back_ios_new`, `done`, `expand_less`, `expand_more`, `file_download_done`, `navigate_before`, `navigate_next`,
`cut`, `emoji_flags`, `feed`, `monetization_on`, `wifi_calling_1`, `wifi_calling_2`, `wifi_calling_3`,
`airplanemode_active`, `clear_night`, `device_reset`, `flightsmode`, `lens`, `panorama_fish_eye`, `quiet_time`,
`quiet_time_active`. Deprecated icons will be logged in console in non production mode. This mapping is susceptible to
change over upgrades, we strongly encourage you to update them.

== Dependencies upgrade

Some dependencies have been upgraded to newer versions. Check the {product-version-changelog}[change log] for detailed
list.

== Others Notable Changes

- Some layout changes in the login page as part of customizations (xref:dev-guide:application/config.adoc#custom-login-page[doc])


== User email now has unique constraint

There is now a unique constraint on the `User` `email` field. You may execute this SQL statement for migration:

[source,sql]
----
UPDATE auth_user SET email = lower(email);
ALTER TABLE auth_user ADD CONSTRAINT uk_auth_user_email UNIQUE (email);
----
