= Development
:toc:
:toc-title:

In this chapter, we will see how to develop axelor applications effectively.

== Requirements

Please check the xref:getting-started:index.adoc[getting started guide] for
pre-requisites and configuring your favourite IDE.

== Run the application

The embedded server is easiest way to run the application during development.

Run the following command in terminal:

[source,sh]
----
$ ./gradlew --no-daemon run
----

IMPORTANT: always execute run task with gradle using `--no-daemon` to avoid application clean up issues (known gradle problem)

After a few seconds, you should see some logs and at the end something like this:

[source,text]
----
...
Ready to serve...

Running at http://localhost:8080/axelor-demo
----

Open the given link in your browser and log in

The run task accepts the following command line options:

* `--port <number>` : alternative port, default to 8080
* `--debug-jvm` : start application in debug mode waiting for debugger on `5005` port. Attach your
favourite Java debugger on this port to start debugging.
* `--config <path>` : specify the application config file path

== XML Hotswap

If you run the app in debug mode as mentioned above, changes to XML views
are hot reloaded. However, you still have to refresh current view with browser refresh button.

Moreover, this feature is experimental and has limitations. For example, it can only detect
XML file changes once the application is started. Any changes done before application start
are not recognized. That issue will be resolved in upcoming releases.
